#!/usr/bin/perl -w
# coverts data generated by 4store's 4s-dump to .nq format

$graph = '';

while( $line = <> ) {
  # e.g., "## GRAPH http://data.bioontology.org/ontologies/PANDA/submissions/2"
  if ($line =~ /## GRAPH (.*)/) {
    print STDERR "Graph is now $1\n";
    $graph = $1;
  } else {
      print substr($line, 0, -2) . "<$graph> .\n";
  }
}
